# ---- Étape 1 : Builder ----
FROM node:22-alpine AS builder
WORKDIR /app
COPY package.json ./
RUN npm install
COPY service_a.js ./

# ---- Étape 2 : Runner ----
FROM node:22-alpine
WORKDIR /app
RUN chown -R node:node /app

# ca sert à changer l'utilisateur pour éviter d'exécuter le conteneur en root, ce qui est une bonne pratique de sécurité
USER node 


COPY --from=builder --chown=node:node /app/node_modules ./node_modules
COPY --from=builder --chown=node:node /app/service_a.js ./

EXPOSE 9090

CMD ["node", "service_a.js"]